return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "1.0.3",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 20,
  height = 22,
  tilewidth = 128,
  tileheight = 128,
  nextobjectid = 181,
  properties = {},
  tilesets = {
    {
      name = "main_sheet",
      firstgid = 1,
      tilewidth = 128,
      tileheight = 128,
      spacing = 0,
      margin = 0,
      image = "tilesheets/sheet1.png",
      imagewidth = 128,
      imageheight = 128,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 128,
        height = 128
      },
      properties = {},
      terrains = {},
      tilecount = 1,
      tiles = {}
    },
    {
      name = "3by3",
      firstgid = 2,
      tilewidth = 128,
      tileheight = 128,
      spacing = 0,
      margin = 4,
      image = "tilesheets/3by3_1.png",
      imagewidth = 392,
      imageheight = 392,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 128,
        height = 128
      },
      properties = {},
      terrains = {},
      tilecount = 9,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "Main_Tiles",
      x = 0,
      y = 0,
      width = 20,
      height = 22,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "lua",
      data = {
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
      }
    },
    {
      type = "objectgroup",
      name = "Window_Size",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      name = "Room",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 131,
          name = "main",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 128,
          width = 2304,
          height = 2560,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "Walls",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 124,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 256,
          height = 1280,
          rotation = 0,
          visible = true,
          properties = {
            right = true,
            down = true
          }
        },
        {
          id = 125,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1664,
          width = 256,
          height = 1152,
          rotation = 0,
          visible = true,
          properties = {
            right = true,
            up = true
          }
        },
        {
          id = 126,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2304,
          y = 0,
          width = 256,
          height = 1280,
          rotation = 0,
          visible = true,
          properties = {
            left = true,
            down = true
          }
        },
        {
          id = 127,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2304,
          y = 1664,
          width = 256,
          height = 1152,
          rotation = 0,
          visible = true,
          properties = {
            left = true,
            up = true
          }
        },
        {
          id = 128,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 2560,
          height = 256,
          rotation = 0,
          visible = true,
          properties = {
            down = true
          }
        },
        {
          id = 129,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 2560,
          width = 1152,
          height = 256,
          rotation = 0,
          visible = true,
          properties = {
            up = true
          }
        },
        {
          id = 130,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1536,
          y = 2560,
          width = 1024,
          height = 256,
          rotation = 0,
          visible = true,
          properties = {
            up = true
          }
        },
        {
          id = 117,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 2176,
          width = 640,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {
            up = true
          }
        },
        {
          id = 118,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1536,
          y = 1792,
          width = 640,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {
            up = true
          }
        },
        {
          id = 119,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 1408,
          width = 512,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {
            up = true
          }
        },
        {
          id = 120,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1664,
          y = 1024,
          width = 640,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {
            up = true
          }
        },
        {
          id = 121,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 640,
          width = 512,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {
            up = true
          }
        }
      }
    },
    {
      type = "objectgroup",
      name = "Transitions",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 114,
          name = "rm1",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1280,
          width = 256,
          height = 384,
          rotation = 0,
          visible = true,
          properties = {
            spawnX = -640,
            spawnY = 0,
            relativeX = 0,
            relativeY = 0
          }
        },
        {
          id = 115,
          name = "rm3",
          type = "",
          shape = "rectangle",
          x = 2304,
          y = 1280,
          width = 256,
          height = 384,
          rotation = 0,
          visible = true,
          properties = {
            spawnX = 384,
            spawnY = 0,
            relativeX = 0,
            relativeY = 0
          }
        },
        {
          id = 116,
          name = "rm4",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 2560,
          width = 384,
          height = 256,
          rotation = 0,
          visible = true,
          properties = {
            spawnX = 0,
            spawnY = 384,
            relativeX = 0,
            relativeY = 0
          }
        }
      }
    },
    {
      type = "objectgroup",
      name = "Pickups",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 123,
          name = "health1",
          type = "",
          shape = "rectangle",
          x = 1920,
          y = 2176,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "Enemies",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 122,
          name = "",
          type = "bat",
          shape = "rectangle",
          x = 768,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {
            arg = 0
          }
        }
      }
    },
    {
      type = "objectgroup",
      name = "Breakables",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      name = "Vines",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    }
  }
}
